spring:
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:mem:store
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop

    # sql을 보여줌
    show-sql: true

    # sql format pretty
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

#logging:
#  level:
#    org.hibernate.SQL: debug
