spring:
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: root!123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create

    # sql을 보여줌
#    show-sql: true

    # sql format pretty
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


